const TYPES = {
  FETCH_DATA: "FETCH_DATA",
  FETCH_CAR: "FECTH_CAR",
  POST_LOGIN: "POST_LOGIN",
  POST_LOGIN_ADMIN: "POST_LOGIN_ADMIN",
  POST_LOGIN_ADMIN_FAILED: "POST_LOGIN_ADMIN_FAILED",
  DATA_SIDEBAR: "DATA_SIDEBAR",
};

export default TYPES;
