const TYPES = {
  FETCH_DATA: "FETCH_DATA",
  POST_LOGIN: "POST_LOGIN",
  POST_LOGIN_ADMIN: "POST_LOGIN_ADMIN",
  POST_LOGIN_ADMIN_FAILED: "POST_LOGIN_ADMIN_FAILED",
  DATA_SIDEBAR: "DATA_SIDEBAR",
  POST_LOGIN_FAILED: "POST_LOGIN_FAILED",
  SET_MESSAGE: "SET_MESSAGE",
  CLEAR_MESSAGE: "CLEAR_MESSAGE",
  DATA_PAYMENT: "DATA_PAYMENT",
  DATA_PAYMENT_UPLOAD: "DATA_PAYMENT_UPLOAD",
  DATA_ORDER_PAYMENT: "DATA_ORDER_PAYMENT",
  DATA_BUKTI_PEMBAYARAN: "DATA_BUKTI_PEMBAYARAN",
  FETCH_CAR: "FECTH_CAR",
  CHANGE_CATEGORY_CAR: "CHANGE_CATEGORY_CAR",
  SEARCH_NAME_CAR: "SEARCH_NAME_CAR",
  CUSTOMER_LOGOUT: "CUSTOMER_LOGOUT",
  ADMIN_LOGOUT: "ADMIN_LOGOUT"
};

export default TYPES;
