const TYPES = {
  FETCH_DATA: "FETCH_DATA",
  FETCH_CAR: "FECTH_CAR",
  POST_LOGIN: "POST_LOGIN",
  POST_LOGIN_ADMIN: "POST_LOGIN_ADMIN",
  POST_LOGIN_ADMIN_FAILED: "POST_LOGIN_ADMIN_FAILED",
  DATA_SIDEBAR: "DATA_SIDEBAR",

  // FETCH_CAR_REQUEST: "FETCH_CAR_REQUEST",
  // FETCH_CAR_SUCCESS: "FETCH_CAR_SUCCESS",
  // FETCH_CAR_FAILED: "FETCH_CAR_FAILED",
};

export default TYPES;
